const ProfData = [
  {
    id: 1,
    name: "공유",
    age: "20",
    desc: ["아 뭐하지", "안녕하세요", "그래그래"],
    imgSrc: "img/공유.png",
    isLike: false,
  },
  {
    id: 2,
    name: "공효진",
    age: "22",
    desc: ["아 뭐하지", "안녕하세요", "그래그래"],
    imgSrc: "img/공효진.png",
    isLike: false,
  },
  {
    id: 3,
    name: "김재욱",
    age: "25",
    desc: ["아 뭐하지", "안녕하세요", "그래그래"],
    imgSrc: "img/김재욱.png",
    isLike: false,
  },
  {
    id: 4,
    name: "서현진",
    age: "28",
    desc: ["아 뭐하지", "안녕하세요", "그래그래"],
    imgSrc: "img/서현진.png",
    isLike: false,
  },
  {
    id: 5,
    name: "이천희",
    age: "30",
    desc: ["아 뭐하지", "안녕하세요", "그래그래"],
    imgSrc: "img/이천희.png",
    isLike: false,
  },
  {
    id: 6,
    name: "이천희",
    age: "30",
    desc: ["아 뭐하지", "안녕하세요", "그래그래"],
    imgSrc: "img/이천희.png",
    isLike: false,
  },
  {
    id: 7,
    name: "이천희",
    age: "30",
    desc: ["아 뭐하지", "안녕하세요", "그래그래"],
    imgSrc: "img/이천희.png",
    isLike: false,
  },
  {
    id: 8,
    name: "이천희",
    age: "30",
    desc: ["아 뭐하지", "안녕하세요", "그래그래"],
    imgSrc: "img/이천희.png",
    isLike: false,
  },
];
export default ProfData;
